<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUe1fvxx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUe1fvxx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUe1fvxx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUe1fvxx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUe1fvxx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ue1fvxx',
    'container.build_id' => 'cd654dc4',
    'container.build_time' => 1589482439,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUe1fvxx');
